spring:
  datasource:
    url: jdbc:postgresql://192.168.1.11:5432/middlewareqa
    username: middlewareqa
    password: desarrollo
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: Apigateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user_service
            uri: lb://USERMS
            predicates:
              - Path=/api/profisca/v1.0/users/**
          - id: mapping_error_service
            uri: lb://MAPPING-ERRORMS
            predicates:
              - Path=/api/v1.0/mappingError/**
          - id: iglesia_service
            uri: lb://IGLESIAMS
            predicates:
              - Path=/api/profisca/v1.0/iglesias/**
          - id: email_service
            uri: lb://EMAILMS
            predicates:
              - Path=/api/profisca/v1.0/emails/**
server:
  tomcat:
    accesslog:
      enabled: true
      directory: /tmp/logs
      prefix: apigateway_access_log.
      suffix: .log  # Corrección de typo
  port: 4443

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://192.168.1.10:8761/eureka}
